### ISSUE TITLE
error setting the name to the resource opc_compute_ip_reservation or opc_compute_ip_association

### ISSUE THREAD

**Issue by adomaceo** [oracle/terraform-provider-compute#10]
Hello,
I have this resource definition:
...
resource "opc_compute_ip_reservation" "ipreservation" {
  name = "${format("ipr-%s%03d", var.srvname, var.srvstart + count.index)}"
  parentpool = "/oracle/public/ippool"
  permanent = true
  count = "${var.cantsrv}"
}

resource "opc_compute_ip_association" "instance-ipreservation" {
  name = "${format("ipa-%s%03d", var.srvname, var.srvstart + count.index)}"
  vcable = "${element(opc_compute_instance.stresthost.*.vcable, count.index)}"
  parentpool = "ipreservation:${element(opc_compute_ip_reservation.ipreservation.*.name, count.index)}"
  count = "${var.cantsrv}"
}
...
The resource creation is OK but the name attribute doesn't work, eg:020d81b3-9c33-4f9d-8fc6-a86f31f76a9b

Terraform v0.9.3

Regards,

**Comment by scross01** [comment]
opc_compute_ip_reservation name attribute is now supported in the built-on opc provider with Terraform  v0.9.4 https://www.terraform.io/docs/providers/opc/r/opc_compute_ip_reservation.html 

For details on migrating from the provider plugin to the built-in opc provider see the [migration guide](https://github.com/oracle/terraform-provider-compute/blob/master/MIGRATION.md)
