### ISSUE TITLE
sec_list missing

### ISSUE THREAD

**Issue by g3rmanp1bon** [oracle/terraform-provider-compute#11]
Hi,

on file main.tf, for instances 3 & 4 must add sec_lists attribute with an already created security list with ssh security application created, otherwise the install_ssh_keys module will not work and returns a timeout

Regards,

German Pabon

**Comment by scross01** [comment]
@g3rmanp1bon I assume you are referring to the [ipnetworks example](https://github.com/oracle/terraform-provider-compute/tree/master/examples/opc/ipnetworks). When there are no security lists explicitly defined then Oracle Compute adds the default security list `/Compute-mydomain/default/default` automatically - which enables ssh by default (unless you are using a GSE demo environment)

**Comment by g3rmanp1bon** [comment]
You're right, It's for the IPNetworks example, btw, excellent example and
yes, I'm using a GSE environment.

The example works ok!!!

Thanks for your clarification!
