### ISSUE TITLE
terraform - Authorization token  invalid error

### ISSUE THREAD

**Issue by tsgmanh** [oracle/terraform-provider-compute#13]
Hi,

I am getting following error when i ran  terraform script.  this error  is getting after 30 minutes when i run the script.
Terraform version - 0.10.0
Provider version - 0.1.2

My script is doing three things
a) creating a snapshot of an existing disk
b using the  snapshot  create a storage volume
c) using the storage volume then create an instance.

Error applying plan:

1 error(s) occurred:
* module.snapshot-restore.opc_compute_storage_volume.opc-restore-data[0]: 1 error(s) occurred:
* opc_compute_storage_volume.opc-restore-data.0: Error creating storage volume sp-demo-data: 401: {"message": "Authorization token is invalid"}

**Comment by tsgmanh** [comment]
Can anybody please help on this?

**Comment by scross01** [comment]
@tsgmanh can you open this issue on the main terraform provider development repo at https://github.com/terraform-providers/terraform-provider-opc repo for the v0.1.2 version of the provider.  This repo is deprecated

**Comment by tsgmanh** [comment]
Thanks. will do that.
