### ISSUE TITLE
Support for IP Address Prefix Sets

### ISSUE THREAD

**Issue by llBIKSll** [oracle/terraform-provider-compute#17]
It will made it more easy if we where able also config Prefix set.

**Comment by scross01** [comment]
The standalone provider in this repo is deprecated.  Development has moved to https://github.com/terraform-providers/terraform-provider-opc 

IP Address Prefix Sets are supported:
https://www.terraform.io/docs/providers/opc/r/opc_compute_ip_address_prefix_set.html
