### ISSUE TITLE
Endpoint user password information inside the tf file 

### ISSUE THREAD

**Issue by mvukadinoff** [oracle/terraform-provider-compute#5]
Hi,
Nice job on the provider for Oracle cloud.
What I think would be nice is to have the option to specify the variables for the provider inside the config file - *.tf 
OPC_IDENTITY_DOMAIN , OPC_ENDPOINT, OPC_USERNAME,OPC_PASSWORD

Something like for the build in AWS one, where you have:

provider "aws" {
  access_key = "xxxx"
  secret_key = "xxxx"
  region     = "xxxx"
}

**Comment by mvukadinoff** [comment]
OK, I looked trough the code. It seems it's already implemented, so I rev. eng'd the needed configuration. It should look something like this:
provider "opc" {
        user = "xxxx@xxx"
        password = "xxxx"
        identityDomain = "xxxx"
        endpoint = "https://api-z18.compute.em3.oraclecloud.com/"
}

**Comment by scross01** [comment]
@mvukadinoff thanks for pointing this out, the README has been updated with the example.
