### ISSUE TITLE
Unknown provider opc error

### ISSUE THREAD

**Issue by bageorge** [oracle/terraform-provider-compute#6]
When I run the command "terraform plan" from the folder "/home/opc/terraform-provider/src/github.com/oracle/terraform/test",  the following error is reported.

Error configuring: 7 error(s) occurred:

* opc_compute_ip_association.instance1_reservation1: provider opc couldn't be found
* opc_compute_security_list.sec_list1: provider opc couldn't be found
* opc_compute_security_association.test_instance__sec_list_1: provider opc couldn't be found
* opc_compute_instance.test_instance: provider opc couldn't be found
* opc_compute_storage_volume.test_volume: provider opc couldn't be found
* opc_compute_storage_volume.test_volume2: provider opc couldn't be found
* opc_compute_ip_reservation.reservation1: provider opc couldn't be found

Is "opc" not a supported provider? I checked the list of providers in "https://www.terraform.io/docs/providers/" page but could not see "opc". 
Please help me .

Thanks
Babu G

**Comment by scross01** [comment]
The opc provider is currently provided as a provider plugin.  You need either have the `terraform-provider-opc` binary in your local directory, or update your terraform configuration file to point to the location of the provider plugin (see [Usage](https://github.com/oracle/terraform-provider-compute#usage))

On MacOS/Linux update `~/.terraformrc` 

```
providers {
    opc = "/home/opc/bin/terraform-provider-opc"
}
```

On Windows update `%APPDATA%\terraform.rc`

```
providers {
    opc = "C:\\Users\\opc\\bin\\terraform-provider-opc.exe"
}
```

Changing the directory location as appropriate.

**Comment by bageorge** [comment]
Thanks for the update. After adding the "terraform-provider-opc" path details in ~/.terraformrc file , the unknown provider is gone, but a new issue is appearing. Following is the complete error message.

[root@tooling-instance test]# terraform plan
Error configuring: 1 error(s) occurred:

* Incompatible API version with plugin. Plugin version: 3, Ours: 2

Terraform version 

[root@tooling-instance test]# terraform -v
Terraform v0.8.7

Am I supposed to download Terraform 0.7.x as documented in the README file 

"[Terraform](https://www.terraform.io/downloads.html) 0.7.x 

Please help.

**Comment by llBIKSll** [comment]
I have the same issue as bageorge. I am just running it from windows.

Error configuring: 1 error(s) occurred:
* Incompatible API version with plugin. Plugin version: 3, Ours: 2

**Comment by bageorge** [comment]
Tried with Terraform 0.7.x versions ( 13 and 12) but ended up in similar error.

**Comment by llBIKSll** [comment]
Yes, I have also just tried with version 0.7.12
Same issue

**Comment by scross01** [comment]
See the notes on [Common Build Issues](https://github.com/oracle/terraform-provider-compute#common-build-issues) 

The problem is because provider is getting built against the latest terraform source, but you have an older version of terraform binary - the workaround is to force the build to use a specific version tag of the terraform source.

I'll update the README to indicate the that provider will work against  0.7.x **and above**

**Comment by llBIKSll** [comment]
Okay,

So first 
git checkout v0.7.12
and then build
go build -o terraform-provider-opc github.com/oracle/terraform-provider-compute/provider

Now it look to work :-)

In the Common Build Issues it just say version 0.8.5
May it can help to change it to 0.7.12

**Comment by scross01** [comment]
It would depend on version of terraform you have installed - latest version is now  0.8.7
